[package]
name = "sensor_simulator"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
rand = "0.9.2"
rand_distr = "0.5.1"
serde = "1.0.219"
time = "0.3.41"
